// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vwaczaqozyuybdirrqix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3YWN6YXFvenl1eWJkaXJycWl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMzU4OTQsImV4cCI6MjA2OTgxMTg5NH0.MzaGHpt5iUM7IDPXxmioD8XlE42lW6Fc5x0ysoP_Rmg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});